BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Sightings" (
	"Id"	INTEGER NOT NULL,
	"City"	TEXT NOT NULL,
	"Country"	TEXT NOT NULL,
	"Duration"	TEXT NOT NULL,
	"Dateposted"	TEXT NOT NULL,
	"Datetime"	TEXT NOT NULL,
	"Comments"	TEXT NOT NULL,
	CONSTRAINT "PK_Sightings" PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
